### ISSUE TITLE
Incompatible with Gradle 4.2

### ISSUE THREAD

**Issue by SlyDen** [jcgay/gradle-notifier#6]
after update to Gradle 4.2 (4.1 is works fine) there is an error 
```
* What went wrong:
Execution failed for task ':run'.
> No signature of method: org.gradle.deployment.internal.DefaultDeploymentRegistry.get() is applicable for argument types: (java.lang.Class, java.lang.String) values: [interface org.gradle.deployment.internal.DeploymentHandle, :run]
  Possible solutions: get(java.lang.String, java.lang.Class), grep(), getAt(java.lang.String), wait(), any(), grep(java.lang.Object)
```
and later 
```
* What went wrong:
Failed to notify build listener.
> org.gradle.util.Clock.getTimeInMs()J
```
So I assume there was a change in API and now `systemtray` parameter `wait` isn't working properly ... digging in.

**Comment by SlyDen** [comment]
It seems like it is not this plugin's issue ... it is something with Gradle 4.2 and my projects config.
Reverted back to 4.1 and keep it for now.

**Comment by SlyDen** [comment]
Reviewed  it again (Gradle 4.2.1) - the problem is here:

```
Caused by: java.lang.NoSuchMethodError: org.gradle.util.Clock.getTimeInMs()J
        at fr.jcgay.gradle.notifier.extension.TimeThreshold.of(TimeThreshold.groovy:36)
```

**Comment by jcgay** [comment]
Thanks for the report.

I remember that I was using a deprecated method, I will have a look if it has been replaced by something else or if I have to remove a functionality!

**Comment by SlyDen** [comment]
yeah ... I didn't find direct replacement. There is a deprecation annotation on the class, but also they removed that method completely in one of the commits before .... I'm not very proficient in Gradle's plugins so wasn't smart enough to find the appropriate method quickly :( ...

**Comment by jcgay** [comment]
I have found the replacement I needed to display the time spent building 😅

It should be fine now with v2.0.0, let me now if it's ok for you too!
Thanks again.

**Comment by SlyDen** [comment]
Confirm - it works 😃  Thank you for the awesome plugin !!

**Comment by jcgay** [comment]
Great 😇, Thanks for the feedback! Hope it helps :)
