### ISSUE TITLE
How to use Notification center with AppleScript?

### ISSUE THREAD

**Issue by toxxmeister** [jcgay/gradle-notifier#8]
In your Wiki you mention that AppleScript is also available as a notifications backend.
How exactly can this be activated?

**Comment by jcgay** [comment]
Yes I should update the document for each notifier to indicate which implementation to configure, it is unclear...

You should be able to use it by setting `notifier.implementation` property to `simplenc `.

**Comment by jcgay** [comment]
Feel free to re-open if it's still actual.
