### ISSUE TITLE
Disable notifications for buildSrc

### ISSUE THREAD

**Issue by toxxmeister** [jcgay/gradle-notifier#9]
Is there any way to disable notifications for buildSrc project?
By default, I get a notification for both the buildSrc project and the actual project I'm building.
I'm aware that setting a small enough threshold could get rid of it, but I'm looking for something more reliable, as I generally don't use the threshold feature at all.

**Comment by jcgay** [comment]
I'm afraid that this case is not handle :)
I'll have a look into it, Do you have any idea how to address this ?

Thx

**Comment by jcgay** [comment]
Let me know if release `v2.2.0` fixes your issue :)

**Comment by toxxmeister** [comment]
Yes, it does. Thank you!
